version: '2'
services:
  7dtdserver:
    container_name: 7dtdserver
    environment:
    - START_MODE=${START_MODE}
    - VERSION=${VERSION}
    - PUID=${PUID}
    - PGID=${PGID}
    - TimeZone=${TimeZone}
    - TEST_ALERT=${TEST_ALERT}
    - UPDATE_MODS=${UPDATE_MODS}
    - ALLOC_FIXES=${ALLOC_FIXES}
    - ALLOC_FIXES_UPDATE
    - UNDEAD_LEGACY=${UNDEAD_LEGACY}
    - UNDEAD_LEGACY_VERSION=${UNDEAD_LEGACY_VERSION}
    - UNDEAD_LEGACY_UPDATE=${UNDEAD_LEGACY_UPDATE}
    - ENZOMBIES=${ENZOMBIES}
    - ENZOMBIES_ADDON_SNUFKIN=${ENZOMBIES_ADDON_SNUFKIN}
    - ENZOMBIES_ADDON_ROBELOTO=${ENZOMBIES_ADDON_ROBELOTO}
    - ENZOMBIES_ADDON_NONUDES=${ENZOMBIES_ADDON_NONUDES}
    - ENZOMBIES_UPDATE=${ENZOMBIES_UPDATE}
    - CPM=${CPM}
    - CPM_UPDATE=${CPM_UPDATE}
    - BEPINEX=${BEPINEX}
    - BEPINEX_UPDATE=${BEPINEX_UPDATE}
    - BACKUP=${BACKUP}
    - MONITOR=${MONITOR}
    image: vinanrra/7dtd-server
    ports:
    - 26900:26900/tcp
    - 26900:26900/udp
    - 26901:26901/udp
    - 26902:26902/udp
    - 8080:8080/tcp
    - 8081:8081/tcp
    - 8082:8082/tcp
    restart: unless-stopped
    volumes:
    - /path/to/folder/7DaysToDie:/home/sdtdserver/.local/share/7DaysToDie/
    - /path/to/folder/LGSM-Config:/home/sdtdserver/lgsm/config-lgsm/sdtdserver
    - /path/to/folder/ServerFiles:/home/sdtdserver/serverfiles/
    - /path/to/folder/log:/home/sdtdserver/log/
    - /path/to/folder/backups:/home/sdtdserver/lgsm/backup/
